name: india_learner
description: A new Flutter application.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  get: ^3.0.0
  pin_code_text_field: ^1.7.0
  shared_preferences: ^0.5.12
  fluttertoast: ^7.1.7
  carousel_slider: ^3.0.0
  flutter_rating_bar: ^3.2.0+1
  http: ^0.12.2
  video_player:
  url_launcher: ^5.7.8
  intl: ^0.16.0
  chewie: ^0.12.1+1
  dio: ^3.0.10
  image_picker: ^0.6.7+22
  image_cropper: ^1.2.0
  flutter_uploader: ^1.2.1
  change_app_package_name: ^0.1.3
  path_provider: ^1.6.28
  ext_storage: ^1.0.3
  permission_handler: ^5.0.1
  flutter_cache_manager: ^2.1.2
  cached_video_player: ^1.0.2+2
  ffi: ^0.1.3
  rxdart: ^0.25.0
  advance_pdf_viewer: ^1.2.0
  sqflite: ^1.3.0+2
  lottie:
  flutter_countdown_timer:
  flutter_restart: ^0.0.3
  flutter_local_notifications:
  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:    icon.png   catJson
  assets:
    - assets/images/Online_classes.jpg
    - assets/images/bank.png
    - assets/images/elearning.png
    - assets/jsonassets/json
    - assets/images/copywriting.png
    - assets/images/icon.png
    - assets/images/download.jpg
    - assets/jsonassets/FaqJson
    - assets/images/school.jpg
    - assets/images/defense.jpg
    - assets/jsonassets/catJson
    - assets/images/ssc.jpg
    - assets/images/state.jpg
    - assets/images/other.jpg
    - assets/images/upsc.jpg
    - assets/images/teachers.jpg
    - assets/images/teacher.jpg
    - assets/images/teacher.png
    - assets/images/elearning baner.jpg
    - assets/jsonassets/browseJson
    - assets/jsonassets/win_lottie.json
    - assets/jsonassets/congrats.json
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
